[package]
name = "tentacle-secio"
version = "0.4.2"
license = "MIT"
description = "Secio encryption protocol for p2p"
authors = ["piaoliu <driftluo@foxmail.com>", "Nervos Core Dev <dev@nervos.org>"]
repository = "https://github.com/nervosnetwork/tentacle"
keywords = ["network", "peer-to-peer"]
categories = ["network-programming", "asynchronous"]
edition = "2018"
build = "build.rs"

[package.metadata.docs.rs]
features = [ "molc" ]
all-features = false
no-default-features = true

[dependencies]
bytes = "0.5"
futures = { version = "0.3.0" }
tokio = { version = "0.2.0", features = ["io-util"] }
tokio-util = { version = "0.3.0", features = ["codec"] }
log = "0.4.1"

flatbuffers = { version = "0.6.0", optional = true }
flatbuffers-verifier = { version = "0.2.0", optional = true }
molecule = { version = "0.6.0", optional = true }

unsigned-varint = "0.3"
bs58 = "0.3.0"

[target.'cfg(unix)'.dependencies]
openssl = "0.10.25"
openssl-sys = "0.9"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rand = "0.7"
secp256k1 = "0.17"
ring = "0.16.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
rand = { version = "0.7", features = ["wasm-bindgen"] }
secpwasm = { version = "0.3.5", package = "libsecp256k1"}
sha2 = "0.9.0"
hmac = "0.9.0"
x25519-dalek = "1.1"
chacha20poly1305 = "0.7"

[dev-dependencies]
env_logger = "0.6"
criterion = "0.3"
tokio = { version = "0.2.0", features = ["tcp", "rt-core", "dns"] }
secpwasm = { version = "0.3.5", package = "libsecp256k1"}
sha2 = "0.9.0"
hmac = "0.9.0"
x25519-dalek = "1.1"
chacha20poly1305 = "0.7"

[features]
default = []
# use flatbuffer to handshake
flatc = [ "flatbuffers", "flatbuffers-verifier" ]
# use molecule to handshake
molc = [ "molecule" ]

[[bench]]
name = "bench"
harness = false
